export const KANJIS = [
  {
    category: "numbers",
    name: "1",
    kanji: "一",
    writed: "いち",
    latin: "ichi",
  },
  {
    category: "numbers",
    name: "2",
    kanji: "二",
    writed: "に",
    latin: "ni",
  },
  {
    category: "numbers",
    name: "3",
    kanji: "三",
    writed: "さｎ",
    latin: "san",
  },
  {
    category: "numbers",
    name: "4",
    kanji: "四",
    writed: "よん/し",
    latin: "yon/shi",
  },
  {
    category: "numbers",
    name: "5",
    kanji: "五",
    writed: "ご",
    latin: "go",
  },
  {
    category: "numbers",
    name: "6",
    kanji: "六",
    writed: "ろく",
    latin: "roku",
  },
  {
    category: "numbers",
    name: "7",
    kanji: "七",
    writed: "なな/しち",
    latin: "nana/shichi",
  },
  {
    category: "numbers",
    name: "8",
    kanji: "八",
    writed: "はち",
    latin: "hachi",
  },
  {
    category: "numbers",
    name: "9",
    kanji: "九",
    writed: "く",
    latin: "ku",
  },
  {
    category: "numbers",
    name: "10",
    kanji: "十",
    writed: "じゅう",
    latin: "juu",
  },
  {
    category: "numbers",
    name: "100",
    kanji: "百",
    writed: "ひゃく",
    latin: "hyaku",
  },
  {
    category: "numbers",
    name: "1000",
    kanji: "千",
    writed: "せん",
    latin: "sen",
  },
];
